-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 09:05:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`COUNTRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`COUNTRY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`COUNTRY` (
  `id_country` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`CITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`CITY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`CITY` (
  `id_city` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fk_country` UUID NOT NULL,
  PRIMARY KEY (`id_city`),
  UNIQUE INDEX `id_city_UNIQUE` (`id_city` ASC) VISIBLE,
  INDEX `fk_country_idx` (`fk_country` ASC) VISIBLE,
  CONSTRAINT `fk_country_city`
    FOREIGN KEY (`fk_country`)
    REFERENCES `proyecto`.`COUNTRY` (`id_country`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`LOCALITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`LOCALITY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`LOCALITY` (
  `id_locality` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fk_city` UUID NOT NULL,
  PRIMARY KEY (`id_locality`),
  UNIQUE INDEX `id_locality_UNIQUE` (`id_locality` ASC) VISIBLE,
  INDEX `fk_city_idx` (`fk_city` ASC) VISIBLE,
  CONSTRAINT `fk_city_locality`
    FOREIGN KEY (`fk_city`)
    REFERENCES `proyecto`.`CITY` (`id_city`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`NEIGHBORHOOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`NEIGHBORHOOD` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`NEIGHBORHOOD` (
  `id_neighborhood` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fk_locality` UUID NOT NULL,
  PRIMARY KEY (`id_neighborhood`),
  UNIQUE INDEX `id_neighborhood_UNIQUE` (`id_neighborhood` ASC) VISIBLE,
  INDEX `fk_neighborhood_idx` (`fk_locality` ASC) VISIBLE,
  CONSTRAINT `fk_locality_neighborhood`
    FOREIGN KEY (`fk_locality`)
    REFERENCES `proyecto`.`LOCALITY` (`id_locality`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`USER` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`USER` (
  `id_user` UUID NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `document_type` VARCHAR(45) NOT NULL,
  `document_number` VARCHAR(45) NOT NULL,
  `fk_neighborhood` UUID NOT NULL,
  `phone` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_neighborhood_idx` (`fk_neighborhood` ASC) VISIBLE,
  CONSTRAINT `fk_neighborhood_user`
    FOREIGN KEY (`fk_neighborhood`)
    REFERENCES `proyecto`.`NEIGHBORHOOD` (`id_neighborhood`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`USERSTATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`USERSTATE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`USERSTATE` (
  `id_user_state` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user_state`),
  UNIQUE INDEX `id_user_state_UNIQUE` (`id_user_state` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCTCATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCTCATEGORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCTCATEGORY` (
  `id_product_category` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `measurement_unity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCT` (
  `id_product` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `stock` DOUBLE NOT NULL,
  `alert_stock` DOUBLE NULL,
  `photo` VARCHAR(45) NULL,
  `fk_product_category` UUID NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_productor_UNIQUE` (`id_product` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_product_category_product_idx` (`fk_product_category` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_product`
    FOREIGN KEY (`fk_product_category`)
    REFERENCES `proyecto`.`PRODUCTCATEGORY` (`id_product_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCTORXPRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCTORXPRODUCT` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCTORXPRODUCT` (
  `id_product` UUID NOT NULL,
  `id_productor` UUID NOT NULL,
  `id_productxproductor` UUID NOT NULL,
  PRIMARY KEY (`id_productxproductor`),
  INDEX `fk_productor_idx` (`id_productor` ASC) VISIBLE,
  CONSTRAINT `fk_product_productorxproduct`
    FOREIGN KEY (`id_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productor_producoxproductor`
    FOREIGN KEY (`id_productor`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCTSTATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCTSTATE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCTSTATE` (
  `id_product_state` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product_state`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCTPRICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCTPRICE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCTPRICE` (
  `id_product_price` UUID NOT NULL,
  `fk_product` UUID NOT NULL,
  `fk_product_state` UUID NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_product_price`),
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  INDEX `fk_product_state_idx` (`fk_product_state` ASC) VISIBLE,
  CONSTRAINT `fk_product_product_price`
    FOREIGN KEY (`fk_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_state_product_price`
    FOREIGN KEY (`fk_product_state`)
    REFERENCES `proyecto`.`PRODUCTSTATE` (`id_product_state`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`COLLECTIONPOINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`COLLECTIONPOINT` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`COLLECTIONPOINT` (
  `id_collection_point` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fk_neighborhood` UUID NOT NULL,
  `use_price` VARCHAR(45) NULL,
  `fk_owner` UUID NOT NULL,
  PRIMARY KEY (`id_collection_point`),
  INDEX `fk_neighborhood_idx` (`fk_neighborhood` ASC) VISIBLE,
  INDEX `fk_owner_idx` (`fk_owner` ASC) VISIBLE,
  CONSTRAINT `fk_neighborhood_collection_point`
    FOREIGN KEY (`fk_neighborhood`)
    REFERENCES `proyecto`.`NEIGHBORHOOD` (`id_neighborhood`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_owner_collection_point`
    FOREIGN KEY (`fk_owner`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`COLLECTIONPOINTSTATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`COLLECTIONPOINTSTATE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`COLLECTIONPOINTSTATE` (
  `id_collection_point_state` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_collection_point_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`NEIGHBORHOODPACKAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`NEIGHBORHOODPACKAGE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`NEIGHBORHOODPACKAGE` (
  `fk_in_charge` UUID NOT NULL,
  `fk_collection_point` UUID NOT NULL,
  `date` DATETIME NOT NULL,
  `id_neighborhood_package` UUID NOT NULL,
  INDEX `fk_collection_point_idx` (`fk_collection_point` ASC) VISIBLE,
  PRIMARY KEY (`id_neighborhood_package`),
  CONSTRAINT `fk_user_neighborhood_package`
    FOREIGN KEY (`fk_in_charge`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_collection_point_neighborhood_package`
    FOREIGN KEY (`fk_collection_point`)
    REFERENCES `proyecto`.`COLLECTIONPOINT` (`id_collection_point`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PURCHASETYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PURCHASETYPE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PURCHASETYPE` (
  `id_purchase_type` UUID NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_purchase_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PAYMENTMETHOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PAYMENTMETHOD` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PAYMENTMETHOD` (
  `id_payment_method` UUID NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_payment_method`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PURCHASE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PURCHASE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PURCHASE` (
  `id_purchase` UUID NOT NULL,
  `fk_user` UUID NOT NULL,
  `fk_type_purchase` UUID NOT NULL,
  `amount` DOUBLE NOT NULL,
  `fk_neighborhood_package` UUID NULL,
  `fk_payment_method` UUID NOT NULL,
  PRIMARY KEY (`id_purchase`),
  INDEX `fk_purchase_type_idx` (`fk_type_purchase` ASC) VISIBLE,
  INDEX `fk_user_idx` (`fk_user` ASC) VISIBLE,
  INDEX `fk_neighborhood_package_purchase_idx` (`fk_neighborhood_package` ASC) VISIBLE,
  INDEX `fk_payment_method_purchase_idx` (`fk_payment_method` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_type_purchase`
    FOREIGN KEY (`fk_type_purchase`)
    REFERENCES `proyecto`.`PURCHASETYPE` (`id_purchase_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_purchase`
    FOREIGN KEY (`fk_user`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_neighborhood_package_purchase`
    FOREIGN KEY (`fk_neighborhood_package`)
    REFERENCES `proyecto`.`NEIGHBORHOODPACKAGE` (`id_neighborhood_package`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_method_purchase`
    FOREIGN KEY (`fk_payment_method`)
    REFERENCES `proyecto`.`PAYMENTMETHOD` (`id_payment_method`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PURCHASEDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PURCHASEDETAIL` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PURCHASEDETAIL` (
  `id_purchase_detail` UUID NOT NULL,
  `fk_product` UUID NOT NULL,
  `quantity` DOUBLE NOT NULL,
  `fk_purchase` UUID NOT NULL,
  PRIMARY KEY (`id_purchase_detail`),
  INDEX `fk_purchase_idx` (`fk_purchase` ASC) VISIBLE,
  INDEX `fk_product_purchase_detail_idx` (`fk_product` ASC) VISIBLE,
  CONSTRAINT `fk_product_purchase_detail`
    FOREIGN KEY (`fk_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_purchase_detail`
    FOREIGN KEY (`fk_purchase`)
    REFERENCES `proyecto`.`PURCHASE` (`id_purchase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`NEIGHBORHOODPACKAGESTATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`NEIGHBORHOODPACKAGESTATE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`NEIGHBORHOODPACKAGESTATE` (
  `id_neighborhood_package_state` UUID NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_neighborhood_package_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`USERHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`USERHISTORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`USERHISTORY` (
  `id_user_history` UUID NOT NULL,
  `fk_user` UUID NOT NULL,
  `fk_user_state` UUID NOT NULL,
  `description` VARCHAR(1500) NULL,
  `init` DATETIME NOT NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id_user_history`),
  INDEX `fk_user_idx` (`fk_user` ASC) VISIBLE,
  INDEX `fk_user_state_idx` (`fk_user_state` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_history`
    FOREIGN KEY (`fk_user`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_state_user_history`
    FOREIGN KEY (`fk_user_state`)
    REFERENCES `proyecto`.`USERSTATE` (`id_user_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`PRODUCTHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`PRODUCTHISTORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`PRODUCTHISTORY` (
  `id_product_history` UUID NOT NULL,
  `fk_product` UUID NOT NULL,
  `fk_product_state` UUID NOT NULL,
  `description` VARCHAR(1500) NULL,
  `init` DATETIME NOT NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id_product_history`),
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  INDEX `fk_product_state_idx` (`fk_product_state` ASC) VISIBLE,
  CONSTRAINT `fk_product_product_history`
    FOREIGN KEY (`fk_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_state_product_history`
    FOREIGN KEY (`fk_product_state`)
    REFERENCES `proyecto`.`PRODUCTSTATE` (`id_product_state`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`STOCKMOVEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`STOCKMOVEMENT` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`STOCKMOVEMENT` (
  `id_stock_movement` UUID NOT NULL,
  `fk_product` UUID NOT NULL,
  `quantity` DOUBLE NOT NULL,
  `type` ENUM('in', 'out', 'edition') NOT NULL,
  `date` DATE NOT NULL,
  `coment` VARCHAR(1500) NULL,
  PRIMARY KEY (`id_stock_movement`),
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  CONSTRAINT `fk_product_stock_movement`
    FOREIGN KEY (`fk_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`NEIGHBORHOODPACKAGEHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`NEIGHBORHOODPACKAGEHISTORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`NEIGHBORHOODPACKAGEHISTORY` (
  `id_neighborhood_package_history` UUID NOT NULL,
  `fk_neighborhood_package` UUID NOT NULL,
  `fk_neighborhood_package_state` UUID NOT NULL,
  `description` VARCHAR(1500) NULL,
  `init` DATETIME NOT NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id_neighborhood_package_history`),
  INDEX `fk_neighborhood_package_idx` (`fk_neighborhood_package` ASC) VISIBLE,
  INDEX `fk_neigborhood_package_state_idx` (`fk_neighborhood_package_state` ASC) VISIBLE,
  CONSTRAINT `fk_neighborhood_package_neigh_pack_hist`
    FOREIGN KEY (`fk_neighborhood_package`)
    REFERENCES `proyecto`.`NEIGHBORHOODPACKAGE` (`id_neighborhood_package`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_neigborhood_package_state_neigh_pack_hist`
    FOREIGN KEY (`fk_neighborhood_package_state`)
    REFERENCES `proyecto`.`NEIGHBORHOODPACKAGESTATE` (`id_neighborhood_package_state`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`COLLECTIONPOINTHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`COLLECTIONPOINTHISTORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`COLLECTIONPOINTHISTORY` (
  `id_collection_point_history` UUID NOT NULL,
  `fk_collection_point` UUID NOT NULL,
  `fk_collection_point_state` UUID NOT NULL,
  `description` VARCHAR(1500) NULL,
  `init` DATETIME NOT NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id_collection_point_history`),
  INDEX `fk_collection_point_idx` (`fk_collection_point` ASC) VISIBLE,
  INDEX `fk_collection_point_state_idx` (`fk_collection_point_state` ASC) VISIBLE,
  CONSTRAINT `fk_collection_point_collection_point_history`
    FOREIGN KEY (`fk_collection_point`)
    REFERENCES `proyecto`.`COLLECTIONPOINT` (`id_collection_point`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_collection_point_state_collection_point_history`
    FOREIGN KEY (`fk_collection_point_state`)
    REFERENCES `proyecto`.`COLLECTIONPOINTSTATE` (`id_collection_point_state`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`SALE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`SALE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`SALE` (
  `id_sale` UUID NOT NULL,
  `amount` DOUBLE NOT NULL,
  `fk_productor` UUID NOT NULL,
  `fk_deliver_guy` UUID NOT NULL,
  `fk_payment_method` UUID NULL,
  `bill` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `fk_user_idx` (`fk_productor` ASC) VISIBLE,
  INDEX `fk_deliver_guy_idx` (`fk_deliver_guy` ASC) VISIBLE,
  INDEX `fk_payment_method_sale_idx` (`fk_payment_method` ASC) VISIBLE,
  CONSTRAINT `fk_user_sale`
    FOREIGN KEY (`fk_productor`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deliver_guy_sale`
    FOREIGN KEY (`fk_deliver_guy`)
    REFERENCES `proyecto`.`USER` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_method_sale`
    FOREIGN KEY (`fk_payment_method`)
    REFERENCES `proyecto`.`PAYMENTMETHOD` (`id_payment_method`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`SALESTATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`SALESTATE` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`SALESTATE` (
  `id_sale_state` UUID NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sale_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`SALEHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`SALEHISTORY` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`SALEHISTORY` (
  `id_sale_history` UUID NOT NULL,
  `fk_sale` UUID NOT NULL,
  `fk_sale_state` UUID NOT NULL,
  `description` VARCHAR(1500) NULL,
  `init` DATETIME NOT NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id_sale_history`),
  INDEX `fk_sale_state_idx` (`fk_sale_state` ASC) VISIBLE,
  INDEX `fk_sale_idx` (`fk_sale` ASC) VISIBLE,
  CONSTRAINT `fk_sale_state_sale_history`
    FOREIGN KEY (`fk_sale_state`)
    REFERENCES `proyecto`.`SALESTATE` (`id_sale_state`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_sale_history`
    FOREIGN KEY (`fk_sale`)
    REFERENCES `proyecto`.`SALE` (`id_sale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`SALEDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`SALEDETAIL` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`SALEDETAIL` (
  `id_sale_detail` UUID NOT NULL,
  `fk_product` UUID NOT NULL,
  `quantity` DOUBLE NOT NULL,
  `fk_sale` UUID NOT NULL,
  PRIMARY KEY (`id_sale_detail`),
  INDEX `fk_sale_idx` (`fk_sale` ASC) VISIBLE,
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  CONSTRAINT `fk_sale_sale_detail`
    FOREIGN KEY (`fk_sale`)
    REFERENCES `proyecto`.`SALE` (`id_sale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_sale_detail`
    FOREIGN KEY (`fk_product`)
    REFERENCES `proyecto`.`PRODUCT` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`COLLECTIONPOINTPAYMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`COLLECTIONPOINTPAYMENTS` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`COLLECTIONPOINTPAYMENTS` (
  `id_collection_point_payments` UUID NOT NULL,
  `fk_collection_point` UUID NOT NULL,
  `date` DATETIME NOT NULL,
  `note` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`id_collection_point_payments`),
  INDEX `fk_collection_point_idx` (`fk_collection_point` ASC) VISIBLE,
  CONSTRAINT `fk_collection_point_collection_point_payment`
    FOREIGN KEY (`fk_collection_point`)
    REFERENCES `proyecto`.`COLLECTIONPOINT` (`id_collection_point`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
